apiVersion: v1
kind: Service
metadata:
  name: pyprojectlb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  selector:
    role: pyproject