name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }}

    - name: Build the latest Docker image
      run: docker build .  --tag wister/pyproject:latest
    - name: Push the latest Docker image
      run: docker push wister/pyproject:latest
